version: 2
jobs:
    build:
        working_directory: ~/spt-ci-support
        docker:
            - image: circleci/openjdk:8-jdk
#            - image: circleci/node:latest
        steps:
            
            # checkout
            - checkout:
                path: ~/spt-ci-support
            - run: |
                cat ./installer/install-circleci-aws-cli.sh | bash 2>&1             | grep aws-cli
            - run: |
                cat ./installer/install-circleci-maven.sh   | bash -s -- 3.3.9      | (( $(grep -c Download) >= 0 ))
                cat ./installer/install-circleci-maven.sh   | bash -s -- 3.3.9      | (( $(grep -c Download) == 0 ))
                cat ./installer/install-circleci-maven.sh   | bash -s -- 3.3.9      | grep 3.3.9
            - run: |
                cat ./installer/install-command.sh          | bash -s -- /usr/local/bin mvn; which mvn-test
  
            
            # dependencies
            - restore_cache:
                keys:
                    - cache-{{ .Branch }}
           
            - save_cache:
                paths:
                    - ~/.m2
                key: cache-{{ .Branch }}
            
            # test
            - run: |
                source ./.circleci/test/ecr-upload-tests.sh
            - run: |
                source ./.circleci/test/ecs-deploy-tests.sh
